version: '3'

services:
  database-carmatrix:
    image: postgres:16.10-alpine3.22
    container_name: database-carmatrix
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: carmatrix
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - network_carmatrix
    restart: unless-stopped
  
  ms-user-carmatrix:
    image: johnnyquinteror16/ms-user-carmatrix:latest
    container_name: ms-user-carmatrix
    depends_on:
      - database-carmatrix
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database-carmatrix:5432/carmatrix
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8082:8082"
    networks:
      - network_carmatrix
    restart: unless-stopped

networks:
  network_carmatrix:
    driver: bridge

volumes:
  postgres_data:
