apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-postgres-carmatrix
  namespace: carmatrix
  labels:
    app: statefulset-postgres-carmatrix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statefulset-postgres-carmatrix
  template:
    metadata:
      labels:
        app: statefulset-postgres-carmatrix
    spec:
      containers:
      - name: statefulset-postgres-carmatrix
        image: postgres:16.10-alpine3.22
        ports:
          - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: secret-carmatrix
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-carmatrix
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: secret-carmatrix
              key: POSTGRES_DB
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: persistent-volume-claim-carmatrix
      - name: init-sql
        configMap:
          name: init-sql-config
---
apiVersion: v1
kind: Service
metadata:
  name: database-carmatrix
  namespace: carmatrix
  labels:
    app: statefulset-postgres-carmatrix
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: statefulset-postgres-carmatrix
  clusterIP: None
