apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-user-carmatrix
  namespace: carmatrix
  labels:
    app: ms-user-carmatrix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-user-carmatrix
  template:
    metadata:
      labels:
        app: ms-user-carmatrix
    spec:
      containers:
      - name: ms-user-carmatrix
        image: johnnyquinteror16/ms-user-carmatrix:latest
        ports:
          - containerPort: 8082
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: config-map-carmatrix
              key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: secret-carmatrix
              key: POSTGRES_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-carmatrix
              key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: ms-user-carmatrix
  namespace: carmatrix
  labels:
    app: ms-user-carmatrix
spec:
  type: NodePort
  selector:
    app: ms-user-carmatrix
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30082